### ISSUE TITLE
Inconsistent evaluation results

### ISSUE THREAD

**Issue by bxkzcb** [Alexadlu/AFter#6]
Hello, I downloaded your tracking results, and then calculated the evaluation indicators with the real labels, and found that the results were inconsistent with your published results. Can you publish your evaluation indicator program?

**Comment by hello-wwy** [comment]
Hi, we use the Python version of the tool for evaluation and it requires the rgbt library to be installed. The address is at https://github.com/opacity-black/RGBT_toolkit. And for VTUAVST since there is no Python version of the tool we use the officially provided program.
